recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
	- osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
	- osxdefaults::menu_add_battery_percentage
	- osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::finder_unhide_home
    global:
        - dotfiles::gitconfig
        - dotfiles::vim
attributes:
    osxdefaults:
        computername: Tembo
    homebrewalt:
        apps:
            - wget
        cask_apps:
            - dropbox
            - alfred
            - spotify
	    - slack
            - hipchat
    dotfiles:
      vim:
          bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color

